# typed: false

# DO NOT EDIT MANUALLY
# This is an autogenerated file for types exported from the `ruby-core` gem.
# Please instead update this file by running `bin/tapioca gem ruby-core`.


# source://shellwords/0.2.2/shellwords.rb#243
class Array
  include ::Enumerable

  def initialize(*_arg0); end

  def &(_arg0); end
  def *(_arg0); end
  def +(_arg0); end
  def -(_arg0); end
  def <<(_arg0); end
  def <=>(_arg0); end
  def ==(_arg0); end
  def [](*_arg0); end
  def []=(*_arg0); end
  def all?(*_arg0); end
  def any?(*_arg0); end
  def append(*_arg0); end
  def assoc(_arg0); end
  def at(_arg0); end
  def bsearch; end
  def bsearch_index; end
  def clear; end
  def collect; end
  def collect!; end
  def combination(_arg0); end
  def compact; end
  def compact!; end
  def concat(*_arg0); end
  def count(*_arg0); end
  def cycle(*_arg0); end
  def deconstruct; end
  def delete(_arg0); end
  def delete_at(_arg0); end
  def delete_if; end
  def detect(*_arg0); end
  def difference(*_arg0); end
  def dig(*_arg0); end
  def drop(_arg0); end
  def drop_while; end
  def each; end
  def each_index; end
  def empty?; end
  def eql?(_arg0); end
  def fetch(*_arg0); end
  def fill(*_arg0); end
  def filter; end
  def filter!; end
  def find(*_arg0); end
  def find_index(*_arg0); end
  def flatten(*_arg0); end
  def flatten!(*_arg0); end
  def freeze; end
  def hash; end
  def include?(_arg0); end
  def index(*_arg0); end
  def insert(*_arg0); end
  def inspect; end
  def intersect?(_arg0); end
  def intersection(*_arg0); end
  def join(*_arg0); end
  def keep_if; end
  def length; end
  def map; end
  def map!; end
  def max(*_arg0); end
  def min(*_arg0); end
  def minmax; end
  def none?(*_arg0); end
  def one?(*_arg0); end
  def permutation(*_arg0); end
  def pop(*_arg0); end
  def prepend(*_arg0); end
  def product(*_arg0); end
  def push(*_arg0); end
  def rassoc(_arg0); end
  def reject; end
  def reject!; end
  def repeated_combination(_arg0); end
  def repeated_permutation(_arg0); end
  def replace(_arg0); end
  def reverse; end
  def reverse!; end
  def reverse_each; end
  def rfind(*_arg0); end
  def rindex(*_arg0); end
  def rotate(*_arg0); end
  def rotate!(*_arg0); end
  def select; end
  def select!; end
  def shift(*_arg0); end
  def size; end
  def slice(*_arg0); end
  def slice!(*_arg0); end
  def sort; end
  def sort!; end
  def sort_by!; end
  def sum(*_arg0); end
  def take(_arg0); end
  def take_while; end
  def to_a; end
  def to_ary; end
  def to_h; end
  def to_s; end
  def transpose; end
  def union(*_arg0); end
  def uniq; end
  def uniq!; end
  def unshift(*_arg0); end
  def values_at(*_arg0); end
  def zip(*_arg0); end
  def |(_arg0); end

  private

  def initialize_copy(_arg0); end

  class << self
    def [](*_arg0); end
    def new(*_arg0); end
    def try_convert(_arg0); end
  end
end

class BasicObject
  def initialize; end

  def !; end
  def !=(_arg0); end
  def ==(_arg0); end
  def __id__; end
  def __send__(*_arg0); end
  def equal?(_arg0); end
  def instance_eval(*_arg0); end
  def instance_exec(*_arg0); end

  private

  def method_missing(*_arg0); end
  def singleton_method_added(_arg0); end
  def singleton_method_removed(_arg0); end
  def singleton_method_undefined(_arg0); end
end

class Binding
  def clone; end
  def dup; end
  def eval(*_arg0); end
  def implicit_parameter_defined?(_arg0); end
  def implicit_parameter_get(_arg0); end
  def implicit_parameters; end
  def local_variable_defined?(_arg0); end
  def local_variable_get(_arg0); end
  def local_variable_set(_arg0, _arg1); end
  def local_variables; end
  def receiver; end
  def source_location; end
end

class Class < ::Module
  def initialize(*_arg0); end

  def allocate; end
  def attached_object; end
  def new(*_arg0); end
  def superclass; end

  private

  def inherited(_arg0); end

  class << self
    def allocate; end
  end
end

module Comparable
  def <(_arg0); end
  def <=(_arg0); end
  def ==(_arg0); end
  def >(_arg0); end
  def >=(_arg0); end
  def between?(_arg0, _arg1); end
  def clamp(*_arg0); end
end

class Complex < ::Numeric
  def *(_arg0); end
  def **(_arg0); end
  def +(_arg0); end
  def -(_arg0); end
  def -@; end
  def /(_arg0); end
  def <=>(_arg0); end
  def ==(_arg0); end
  def abs; end
  def abs2; end
  def angle; end
  def arg; end
  def coerce(_arg0); end
  def conj; end
  def conjugate; end
  def denominator; end
  def eql?(_arg0); end
  def fdiv(_arg0); end
  def finite?; end
  def hash; end
  def imag; end
  def imaginary; end
  def infinite?; end
  def inspect; end
  def magnitude; end
  def numerator; end
  def phase; end
  def polar; end
  def quo(_arg0); end
  def rationalize(*_arg0); end
  def real; end
  def real?; end
  def rect; end
  def rectangular; end
  def to_c; end
  def to_f; end
  def to_i; end
  def to_r; end
  def to_s; end

  private

  def marshal_dump; end

  class << self
    def polar(*_arg0); end
    def rect(*_arg0); end
    def rectangular(*_arg0); end

    private

    def convert(*_arg0); end
  end
end

class Data
  def initialize(*_arg0); end

  def ==(_arg0); end
  def deconstruct; end
  def deconstruct_keys(_arg0); end
  def eql?(_arg0); end
  def hash; end
  def inspect; end
  def members; end
  def to_h; end
  def to_s; end
  def with(*_arg0); end

  private

  def initialize_copy(_arg0); end

  class << self
    def define(*_arg0); end
  end
end

# source://tmpdir/0.3.1/tmpdir.rb#14
class Dir
  include ::Enumerable

  def chdir; end
  def children; end
  def close; end
  def each; end
  def each_child; end
  def fileno; end
  def inspect; end
  def path; end
  def pos; end
  def pos=(_arg0); end
  def read; end
  def rewind; end
  def seek(_arg0); end
  def tell; end
  def to_path; end

  class << self
    def chdir(*_arg0); end
    def children(*_arg0); end
    def chroot(_arg0); end
    def delete(_arg0); end
    def each_child(*_arg0); end
    def empty?(_arg0); end
    def entries(*_arg0); end
    def exist?(_arg0); end
    def fchdir(_arg0); end
    def for_fd(_arg0); end
    def foreach(*_arg0); end
    def getwd; end
    def home(*_arg0); end
    def mkdir(*_arg0); end
    def pwd; end
    def rmdir(_arg0); end
    def unlink(_arg0); end
  end
end

class Encoding
  def _dump(*_arg0); end
  def ascii_compatible?; end
  def dummy?; end
  def inspect; end
  def name; end
  def names; end
  def to_s; end

  class << self
    def _load(_arg0); end
    def aliases; end
    def compatible?(_arg0, _arg1); end
    def default_external; end
    def default_external=(_arg0); end
    def default_internal; end
    def default_internal=(_arg0); end
    def find(_arg0); end
    def list; end
    def locale_charmap; end
    def name_list; end
  end
end

module Enumerable
  extend ::ActiveSupport::EnumerableCoreExt::Constants

  def all?(*_arg0); end
  def any?(*_arg0); end
  def chain(*_arg0); end
  def chunk; end
  def chunk_while; end
  def collect; end
  def collect_concat; end
  def compact; end
  def count(*_arg0); end
  def cycle(*_arg0); end
  def detect(*_arg0); end
  def drop(_arg0); end
  def drop_while; end
  def each_cons(_arg0); end
  def each_entry(*_arg0); end
  def each_slice(_arg0); end
  def each_with_index(*_arg0); end
  def each_with_object(_arg0); end
  def entries(*_arg0); end
  def filter; end
  def filter_map; end
  def find(*_arg0); end
  def find_all; end
  def find_index(*_arg0); end
  def first(*_arg0); end
  def flat_map; end
  def grep(_arg0); end
  def grep_v(_arg0); end
  def group_by; end
  def include?(_arg0); end
  def inject(*_arg0); end
  def lazy; end
  def map; end
  def max(*_arg0); end
  def max_by(*_arg0); end
  def member?(_arg0); end
  def min(*_arg0); end
  def min_by(*_arg0); end
  def minmax; end
  def minmax_by; end
  def none?(*_arg0); end
  def one?(*_arg0); end
  def partition; end
  def reduce(*_arg0); end
  def reject; end
  def reverse_each(*_arg0); end
  def select; end
  def slice_after(*_arg0); end
  def slice_before(*_arg0); end
  def slice_when; end
  def sort; end
  def sort_by; end
  def sum(*_arg0); end
  def take(_arg0); end
  def take_while; end
  def tally(*_arg0); end
  def to_a(*_arg0); end
  def to_h(*_arg0); end
  def uniq; end
  def zip(*_arg0); end
end

class Enumerator
  include ::Enumerable

  def initialize(*_arg0); end

  def +(_arg0); end
  def each(*_arg0); end
  def each_with_index; end
  def each_with_object(_arg0); end
  def feed(_arg0); end
  def inspect; end
  def next; end
  def next_values; end
  def peek; end
  def peek_values; end
  def rewind; end
  def size; end
  def with_index(*_arg0); end
  def with_object(_arg0); end

  private

  def initialize_copy(_arg0); end

  class << self
    def produce(*_arg0); end
    def product(*_arg0); end
  end
end

class Exception
  def initialize(*_arg0); end

  def ==(_arg0); end
  def backtrace; end
  def backtrace_locations; end
  def cause; end
  def detailed_message(*_arg0); end
  def exception(*_arg0); end
  def full_message(*_arg0); end
  def inspect; end
  def message; end
  def respond_to?(*_arg0); end
  def set_backtrace(_arg0); end
  def to_s; end

  private

  def method_missing(*_arg0); end
  def respond_to_missing?(_arg0, _arg1); end

  class << self
    def exception(*_arg0); end
    def to_tty?; end
  end
end

class FalseClass
  def &(_arg0); end
  def ===(_arg0); end
  def ^(_arg0); end
  def inspect; end
  def to_s; end
  def |(_arg0); end
end

class Fiber
  def initialize(*_arg0); end

  def alive?; end
  def backtrace(*_arg0); end
  def backtrace_locations(*_arg0); end
  def blocking?; end
  def inspect; end
  def kill; end
  def raise(*_arg0); end
  def resume(*_arg0); end
  def storage; end
  def storage=(_arg0); end
  def to_s; end
  def transfer(*_arg0); end

  class << self
    def [](_arg0); end
    def []=(_arg0, _arg1); end
    def blocking; end
    def blocking?; end
    def current; end
    def current_scheduler; end
    def schedule(*_arg0); end
    def scheduler; end
    def set_scheduler(_arg0); end
    def yield(*_arg0); end
  end
end

class File < ::IO
  def initialize(*_arg0); end

  def atime; end
  def birthtime; end
  def chmod(_arg0); end
  def chown(_arg0, _arg1); end
  def ctime; end
  def flock(_arg0); end
  def lstat; end
  def mtime; end
  def size; end
  def truncate(_arg0); end

  class << self
    def absolute_path(*_arg0); end
    def absolute_path?(_arg0); end
    def atime(_arg0); end
    def basename(*_arg0); end
    def birthtime(_arg0); end
    def blockdev?(_arg0); end
    def chardev?(_arg0); end
    def chmod(*_arg0); end
    def chown(*_arg0); end
    def ctime(_arg0); end
    def delete(*_arg0); end
    def directory?(_arg0); end
    def dirname(*_arg0); end
    def empty?(_arg0); end
    def executable?(_arg0); end
    def executable_real?(_arg0); end
    def exist?(_arg0); end
    def expand_path(*_arg0); end
    def extname(_arg0); end
    def file?(_arg0); end
    def fnmatch(*_arg0); end
    def fnmatch?(*_arg0); end
    def ftype(_arg0); end
    def grpowned?(_arg0); end
    def identical?(_arg0, _arg1); end
    def join(*_arg0); end
    def lchmod(*_arg0); end
    def lchown(*_arg0); end
    def link(_arg0, _arg1); end
    def lstat(_arg0); end
    def lutime(*_arg0); end
    def mkfifo(*_arg0); end
    def mtime(_arg0); end
    def owned?(_arg0); end
    def path(_arg0); end
    def pipe?(_arg0); end
    def readable?(_arg0); end
    def readable_real?(_arg0); end
    def readlink(_arg0); end
    def realdirpath(*_arg0); end
    def realpath(*_arg0); end
    def rename(_arg0, _arg1); end
    def setgid?(_arg0); end
    def setuid?(_arg0); end
    def size(_arg0); end
    def size?(_arg0); end
    def socket?(_arg0); end
    def split(_arg0); end
    def stat(_arg0); end
    def sticky?(_arg0); end
    def symlink(_arg0, _arg1); end
    def symlink?(_arg0); end
    def truncate(_arg0, _arg1); end
    def umask(*_arg0); end
    def unlink(*_arg0); end
    def utime(*_arg0); end
    def world_readable?(_arg0); end
    def world_writable?(_arg0); end
    def writable?(_arg0); end
    def writable_real?(_arg0); end
    def zero?(_arg0); end
  end
end

class Float < ::Numeric
  def %(_arg0); end
  def *(_arg0); end
  def **(_arg0); end
  def +(_arg0); end
  def -(_arg0); end
  def /(_arg0); end
  def <(_arg0); end
  def <=(_arg0); end
  def <=>(_arg0); end
  def ==(_arg0); end
  def ===(_arg0); end
  def >(_arg0); end
  def >=(_arg0); end
  def angle; end
  def arg; end
  def ceil(*_arg0); end
  def coerce(_arg0); end
  def denominator; end
  def divmod(_arg0); end
  def eql?(_arg0); end
  def fdiv(_arg0); end
  def finite?; end
  def floor(*_arg0); end
  def hash; end
  def infinite?; end
  def inspect; end
  def modulo(_arg0); end
  def nan?; end
  def next_float; end
  def numerator; end
  def phase; end
  def prev_float; end
  def quo(_arg0); end
  def rationalize(*_arg0); end
  def round(*_arg0); end
  def to_i; end
  def to_int; end
  def to_r; end
  def to_s; end
  def truncate(*_arg0); end
end

module GC
  class << self
    def auto_compact; end
    def auto_compact=(_arg0); end
    def compact; end
    def latest_compact_info; end
    def verify_compaction_references(*_arg0); end
    def verify_internal_consistency; end
  end
end

class Hash
  include ::Enumerable

  def <(_arg0); end
  def <=(_arg0); end
  def ==(_arg0); end
  def >(_arg0); end
  def >=(_arg0); end
  def [](_arg0); end
  def []=(_arg0, _arg1); end
  def any?(*_arg0); end
  def assoc(_arg0); end
  def clear; end
  def compact; end
  def compact!; end
  def compare_by_identity; end
  def compare_by_identity?; end
  def deconstruct_keys(_arg0); end
  def default(*_arg0); end
  def default=(_arg0); end
  def default_proc; end
  def default_proc=(_arg0); end
  def delete(_arg0); end
  def delete_if; end
  def dig(*_arg0); end
  def each; end
  def each_key; end
  def each_pair; end
  def each_value; end
  def empty?; end
  def eql?(_arg0); end
  def except(*_arg0); end
  def fetch(*_arg0); end
  def fetch_values(*_arg0); end
  def filter; end
  def filter!; end
  def flatten(*_arg0); end
  def freeze; end
  def has_key?(_arg0); end
  def has_value?(_arg0); end
  def hash; end
  def include?(_arg0); end
  def inspect; end
  def invert; end
  def keep_if; end
  def key(_arg0); end
  def key?(_arg0); end
  def keys; end
  def length; end
  def member?(_arg0); end
  def merge(*_arg0); end
  def merge!(*_arg0); end
  def rassoc(_arg0); end
  def rehash; end
  def reject; end
  def reject!; end
  def replace(_arg0); end
  def select; end
  def select!; end
  def shift; end
  def size; end
  def slice(*_arg0); end
  def store(_arg0, _arg1); end
  def to_a; end
  def to_h; end
  def to_hash; end
  def to_proc; end
  def to_s; end
  def transform_keys(*_arg0); end
  def transform_keys!(*_arg0); end
  def transform_values; end
  def transform_values!; end
  def update(*_arg0); end
  def value?(_arg0); end
  def values; end
  def values_at(*_arg0); end

  private

  def initialize_copy(_arg0); end

  class << self
    def [](*_arg0); end
    def ruby2_keywords_hash(_arg0); end
    def ruby2_keywords_hash?(_arg0); end
    def try_convert(_arg0); end
  end
end

class IO
  include ::Enumerable
  include ::File::Constants

  def initialize(*_arg0); end

  def <<(_arg0); end
  def advise(*_arg0); end
  def autoclose=(_arg0); end
  def autoclose?; end
  def binmode; end
  def binmode?; end
  def close; end
  def close_on_exec=(_arg0); end
  def close_on_exec?; end
  def close_read; end
  def close_write; end
  def closed?; end
  def each(*_arg0); end
  def each_byte; end
  def each_char; end
  def each_codepoint; end
  def each_line(*_arg0); end
  def eof; end
  def eof?; end
  def external_encoding; end
  def fcntl(*_arg0); end
  def fdatasync; end
  def fileno; end
  def flush; end
  def fsync; end
  def getbyte; end
  def getc; end
  def gets(*_arg0); end
  def inspect; end
  def internal_encoding; end
  def ioctl(*_arg0); end
  def isatty; end
  def lineno; end
  def lineno=(_arg0); end
  def path; end
  def pid; end
  def pos; end
  def pos=(_arg0); end
  def pread(*_arg0); end
  def print(*_arg0); end
  def printf(*_arg0); end
  def putc(_arg0); end
  def puts(*_arg0); end
  def pwrite(_arg0, _arg1); end
  def read(*_arg0); end
  def readbyte; end
  def readchar; end
  def readlines(*_arg0); end
  def readpartial(*_arg0); end
  def reopen(*_arg0); end
  def rewind; end
  def seek(*_arg0); end
  def set_encoding(*_arg0); end
  def set_encoding_by_bom; end
  def stat; end
  def sync; end
  def sync=(_arg0); end
  def sysread(*_arg0); end
  def sysseek(*_arg0); end
  def syswrite(_arg0); end
  def tell; end
  def timeout; end
  def timeout=(_arg0); end
  def to_i; end
  def to_io; end
  def to_path; end
  def tty?; end
  def ungetbyte(_arg0); end
  def ungetc(_arg0); end
  def wait(*_arg0); end
  def wait_priority(*_arg0); end
  def wait_readable(*_arg0); end
  def wait_writable(*_arg0); end
  def write(*_arg0); end

  private

  def initialize_copy(_arg0); end

  class << self
    def binread(*_arg0); end
    def binwrite(*_arg0); end
    def copy_stream(*_arg0); end
    def for_fd(*_arg0); end
    def foreach(*_arg0); end
    def new(*_arg0); end
    def open(*_arg0); end
    def pipe(*_arg0); end
    def popen(*_arg0); end
    def read(*_arg0); end
    def readlines(*_arg0); end
    def select(*_arg0); end
    def sysopen(*_arg0); end
    def try_convert(_arg0); end
    def write(*_arg0); end
  end
end

# source://openssl/4.0.0/openssl/bn.rb#33
class Integer < ::Numeric
  def %(_arg0); end
  def &(_arg0); end
  def *(_arg0); end
  def **(_arg0); end
  def +(_arg0); end
  def -(_arg0); end
  def /(_arg0); end
  def <(_arg0); end
  def <<(_arg0); end
  def <=(_arg0); end
  def <=>(_arg0); end
  def ==(_arg0); end
  def ===(_arg0); end
  def >(_arg0); end
  def >=(_arg0); end
  def >>(_arg0); end
  def [](*_arg0); end
  def ^(_arg0); end
  def allbits?(_arg0); end
  def anybits?(_arg0); end
  def ceil(*_arg0); end
  def chr(*_arg0); end
  def coerce(_arg0); end
  def digits(*_arg0); end
  def div(_arg0); end
  def divmod(_arg0); end
  def downto(_arg0); end
  def fdiv(_arg0); end
  def floor(*_arg0); end
  def gcd(_arg0); end
  def gcdlcm(_arg0); end
  def inspect(*_arg0); end
  def lcm(_arg0); end
  def modulo(_arg0); end
  def next; end
  def nobits?(_arg0); end
  def pow(*_arg0); end
  def pred; end
  def rationalize(*_arg0); end
  def remainder(_arg0); end
  def round(*_arg0); end
  def succ; end
  def to_f; end
  def to_r; end
  def to_s(*_arg0); end
  def truncate(*_arg0); end
  def upto(_arg0); end
  def |(_arg0); end

  class << self
    def sqrt(_arg0); end
    def try_convert(_arg0); end
  end
end

module Kernel
  def !~(_arg0); end
  def <=>(_arg0); end
  def ===(_arg0); end
  def define_singleton_method(*_arg0); end
  def display(*_arg0); end
  def dup; end
  def enum_for(*_arg0); end
  def eql?(_arg0); end
  def extend(*_arg0); end
  def freeze; end
  def hash; end
  def inspect; end
  def instance_of?(_arg0); end
  def instance_variable_defined?(_arg0); end
  def instance_variable_get(_arg0); end
  def instance_variable_set(_arg0, _arg1); end
  def instance_variables; end
  def is_a?(_arg0); end
  def itself; end
  def kind_of?(_arg0); end
  def method(_arg0); end
  def methods(*_arg0); end
  def nil?; end
  def object_id; end
  def private_methods(*_arg0); end
  def protected_methods(*_arg0); end
  def public_method(_arg0); end
  def public_methods(*_arg0); end
  def public_send(*_arg0); end
  def remove_instance_variable(_arg0); end
  def respond_to?(*_arg0); end
  def send(*_arg0); end
  def singleton_class; end
  def singleton_method(_arg0); end
  def singleton_methods(*_arg0); end
  def to_enum(*_arg0); end
  def to_s; end

  private

  def Array(_arg0); end
  def Complex(*_arg0); end
  def Hash(_arg0); end
  def Rational(*_arg0); end
  def String(_arg0); end
  def __callee__; end
  def __dir__; end
  def __method__; end
  def `(_arg0); end
  def at_exit; end
  def autoload(_arg0, _arg1); end
  def autoload?(*_arg0); end
  def binding; end
  def block_given?; end
  def caller(*_arg0); end
  def caller_locations(*_arg0); end
  def catch(*_arg0); end
  def eval(*_arg0); end
  def exec(*_arg0); end
  def exit!(*_arg0); end
  def fail(*_arg0); end
  def fork; end
  def format(*_arg0); end
  def gem_original_require(_arg0); end
  def gets(*_arg0); end
  def global_variables; end
  def initialize_clone(*_arg0); end
  def initialize_copy(_arg0); end
  def initialize_dup(_arg0); end
  def instance_variables_to_inspect; end
  def iterator?; end
  def lambda; end
  def load(*_arg0); end
  def local_variables; end
  def open(*_arg0); end
  def p(*_arg0); end
  def print(*_arg0); end
  def printf(*_arg0); end
  def proc; end
  def putc(_arg0); end
  def puts(*_arg0); end
  def raise(*_arg0); end
  def rand(*_arg0); end
  def readline(*_arg0); end
  def readlines(*_arg0); end
  def require_relative(_arg0); end
  def respond_to_missing?(_arg0, _arg1); end
  def select(*_arg0); end
  def set_trace_func(_arg0); end
  def sleep(*_arg0); end
  def spawn(*_arg0); end
  def sprintf(*_arg0); end
  def srand(*_arg0); end
  def syscall; end
  def system(*_arg0); end
  def test(*_arg0); end
  def throw(*_arg0); end
  def trace_var(*_arg0); end
  def trap(*_arg0); end
  def untrace_var(*_arg0); end

  class << self
    def Array(_arg0); end
    def Complex(*_arg0); end
    def Hash(_arg0); end
    def Rational(*_arg0); end
    def String(_arg0); end
    def __callee__; end
    def __dir__; end
    def __method__; end
    def `(_arg0); end
    def abort(*_arg0); end
    def at_exit; end
    def autoload(_arg0, _arg1); end
    def autoload?(*_arg0); end
    def binding; end
    def block_given?; end
    def caller(*_arg0); end
    def caller_locations(*_arg0); end
    def catch(*_arg0); end
    def eval(*_arg0); end
    def exec(*_arg0); end
    def exit(*_arg0); end
    def exit!(*_arg0); end
    def fail(*_arg0); end
    def fork; end
    def format(*_arg0); end
    def gets(*_arg0); end
    def global_variables; end
    def iterator?; end
    def lambda; end
    def load(*_arg0); end
    def local_variables; end
    def no_warning_require(_arg0); end
    def open(*_arg0); end
    def p(*_arg0); end
    def print(*_arg0); end
    def printf(*_arg0); end
    def proc; end
    def putc(_arg0); end
    def puts(*_arg0); end
    def raise(*_arg0); end
    def rand(*_arg0); end
    def readline(*_arg0); end
    def readlines(*_arg0); end
    def require_relative(_arg0); end
    def select(*_arg0); end
    def set_trace_func(_arg0); end
    def sleep(*_arg0); end
    def spawn(*_arg0); end
    def sprintf(*_arg0); end
    def srand(*_arg0); end
    def syscall; end
    def system(*_arg0); end
    def test(*_arg0); end
    def throw(*_arg0); end
    def trace_var(*_arg0); end
    def trap(*_arg0); end
    def untrace_var(*_arg0); end
  end
end

module Marshal
  private

  def dump(*_arg0); end

  class << self
    def dump(*_arg0); end
  end
end

class MatchData
  def ==(_arg0); end
  def [](*_arg0); end
  def begin(_arg0); end
  def bytebegin(_arg0); end
  def byteend(_arg0); end
  def byteoffset(_arg0); end
  def captures; end
  def deconstruct; end
  def deconstruct_keys(_arg0); end
  def end(_arg0); end
  def eql?(_arg0); end
  def hash; end
  def inspect; end
  def length; end
  def match(_arg0); end
  def match_length(_arg0); end
  def named_captures(*_arg0); end
  def names; end
  def offset(_arg0); end
  def post_match; end
  def pre_match; end
  def regexp; end
  def size; end
  def string; end
  def to_a; end
  def to_s; end
  def values_at(*_arg0); end

  private

  def initialize_copy(_arg0); end
end

class Method
  def <<(_arg0); end
  def ==(_arg0); end
  def ===(*_arg0); end
  def >>(_arg0); end
  def [](*_arg0); end
  def arity; end
  def box; end
  def call(*_arg0); end
  def clone; end
  def curry(*_arg0); end
  def dup; end
  def eql?(_arg0); end
  def hash; end
  def inspect; end
  def name; end
  def original_name; end
  def owner; end
  def parameters; end
  def receiver; end
  def source_location; end
  def super_method; end
  def to_proc; end
  def to_s; end
  def unbind; end
end

class Module
  def initialize; end

  def <(_arg0); end
  def <=(_arg0); end
  def <=>(_arg0); end
  def ==(_arg0); end
  def ===(_arg0); end
  def >(_arg0); end
  def >=(_arg0); end
  def alias_method(_arg0, _arg1); end
  def ancestors; end
  def attr(*_arg0); end
  def attr_accessor(*_arg0); end
  def attr_reader(*_arg0); end
  def attr_writer(*_arg0); end
  def autoload?(*_arg0); end
  def autoload_without_tapioca(_arg0, _arg1); end
  def class_eval(*_arg0); end
  def class_exec(*_arg0); end
  def class_variable_defined?(_arg0); end
  def class_variable_get(_arg0); end
  def class_variable_set(_arg0, _arg1); end
  def class_variables(*_arg0); end
  def const_defined?(*_arg0); end
  def const_get(*_arg0); end
  def const_missing(_arg0); end
  def const_set(_arg0, _arg1); end
  def const_source_location(*_arg0); end
  def constants(*_arg0); end
  def define_method(*_arg0); end
  def deprecate_constant(*_arg0); end
  def freeze; end
  def include(*_arg0); end
  def include?(_arg0); end
  def included_modules; end
  def inspect; end
  def instance_method(_arg0); end
  def instance_methods(*_arg0); end
  def method_defined?(*_arg0); end
  def module_eval(*_arg0); end
  def module_exec(*_arg0); end
  def name; end
  def prepend(*_arg0); end
  def private_class_method(*_arg0); end
  def private_constant(*_arg0); end
  def private_instance_methods(*_arg0); end
  def private_method_defined?(*_arg0); end
  def protected_instance_methods(*_arg0); end
  def protected_method_defined?(*_arg0); end
  def public_class_method(*_arg0); end
  def public_constant(*_arg0); end
  def public_instance_method(_arg0); end
  def public_instance_methods(*_arg0); end
  def public_method_defined?(*_arg0); end
  def refinements; end
  def remove_class_variable(_arg0); end
  def remove_method(*_arg0); end
  def set_temporary_name(_arg0); end
  def singleton_class?; end
  def to_s; end
  def undef_method(*_arg0); end
  def undefined_instance_methods; end

  private

  def extended(_arg0); end
  def included(_arg0); end
  def initialize_clone(*_arg0); end
  def method_removed(_arg0); end
  def method_undefined(_arg0); end
  def module_function(*_arg0); end
  def prepended(_arg0); end
  def private(*_arg0); end
  def protected(*_arg0); end
  def public(*_arg0); end
  def refine(_arg0); end
  def remove_const(_arg0); end
  def ruby2_keywords(*_arg0); end
  def using(_arg0); end

  class << self
    def constants(*_arg0); end
    def nesting; end
    def used_modules; end
    def used_refinements; end
  end
end

class NilClass
  def &(_arg0); end
  def ===(_arg0); end
  def =~(_arg0); end
  def ^(_arg0); end
  def inspect; end
  def nil?; end
  def to_a; end
  def to_h; end
  def to_s; end
  def |(_arg0); end
end

class Numeric
  include ::Comparable

  def %(_arg0); end
  def -@; end
  def <=>(_arg0); end
  def abs; end
  def abs2; end
  def angle; end
  def arg; end
  def ceil(*_arg0); end
  def clone(*_arg0); end
  def coerce(_arg0); end
  def denominator; end
  def div(_arg0); end
  def divmod(_arg0); end
  def eql?(_arg0); end
  def fdiv(_arg0); end
  def floor(*_arg0); end
  def i; end
  def magnitude; end
  def modulo(_arg0); end
  def negative?; end
  def nonzero?; end
  def numerator; end
  def phase; end
  def polar; end
  def positive?; end
  def quo(_arg0); end
  def rect; end
  def rectangular; end
  def remainder(_arg0); end
  def round(*_arg0); end
  def singleton_method_added(_arg0); end
  def step(*_arg0); end
  def to_c; end
  def to_int; end
  def truncate(*_arg0); end
  def zero?; end
end

class Object < ::BasicObject
  include ::Kernel
  include ::PP::ObjectMixin
end

module ObjectSpace
  private

  def _id2ref(_arg0); end
  def count_objects(*_arg0); end
  def define_finalizer(*_arg0); end
  def each_object(*_arg0); end
  def undefine_finalizer(_arg0); end

  class << self
    def _id2ref(_arg0); end
    def count_objects(*_arg0); end
    def define_finalizer(*_arg0); end
    def each_object(*_arg0); end
    def undefine_finalizer(_arg0); end
  end
end

class Proc
  def <<(_arg0); end
  def ==(_arg0); end
  def ===(*_arg0); end
  def >>(_arg0); end
  def [](*_arg0); end
  def arity; end
  def binding; end
  def call(*_arg0); end
  def clone; end
  def curry(*_arg0); end
  def dup; end
  def eql?(_arg0); end
  def hash; end
  def inspect; end
  def lambda?; end
  def parameters(*_arg0); end
  def ruby2_keywords; end
  def source_location; end
  def to_proc; end
  def to_s; end
  def yield(*_arg0); end

  class << self
    def new(*_arg0); end
  end
end

module Process
  extend ::SQLite3::ForkSafety::CoreExt
  extend ::ConnectionPool::ForkTracker
  extend ::RedisClient::PIDCache::CoreExt
  extend ::ActiveSupport::ForkTracker::CoreExt

  private

  def argv0; end
  def clock_getres(*_arg0); end
  def clock_gettime(*_arg0); end
  def daemon(*_arg0); end
  def detach(_arg0); end
  def egid; end
  def egid=(_arg0); end
  def euid; end
  def euid=(_arg0); end
  def getpgid(_arg0); end
  def getpgrp; end
  def getpriority(_arg0, _arg1); end
  def getrlimit(_arg0); end
  def getsid(*_arg0); end
  def gid; end
  def gid=(_arg0); end
  def groups; end
  def groups=(_arg0); end
  def initgroups(_arg0, _arg1); end
  def kill(*_arg0); end
  def maxgroups; end
  def maxgroups=(_arg0); end
  def pid; end
  def ppid; end
  def setpgid(_arg0, _arg1); end
  def setpgrp; end
  def setpriority(_arg0, _arg1, _arg2); end
  def setproctitle(_arg0); end
  def setrlimit(*_arg0); end
  def setsid; end
  def times; end
  def uid; end
  def uid=(_arg0); end
  def wait(*_arg0); end
  def wait2(*_arg0); end
  def waitall; end
  def waitpid(*_arg0); end
  def waitpid2(*_arg0); end
  def warmup; end

  class << self
    def abort(*_arg0); end
    def argv0; end
    def clock_getres(*_arg0); end
    def clock_gettime(*_arg0); end
    def daemon(*_arg0); end
    def detach(_arg0); end
    def egid; end
    def egid=(_arg0); end
    def euid; end
    def euid=(_arg0); end
    def exec(*_arg0); end
    def exit(*_arg0); end
    def exit!(*_arg0); end
    def fork; end
    def getpgid(_arg0); end
    def getpgrp; end
    def getpriority(_arg0, _arg1); end
    def getrlimit(_arg0); end
    def getsid(*_arg0); end
    def gid; end
    def gid=(_arg0); end
    def groups; end
    def groups=(_arg0); end
    def initgroups(_arg0, _arg1); end
    def kill(*_arg0); end
    def last_status; end
    def maxgroups; end
    def maxgroups=(_arg0); end
    def pid; end
    def ppid; end
    def setpgid(_arg0, _arg1); end
    def setpgrp; end
    def setpriority(_arg0, _arg1, _arg2); end
    def setproctitle(_arg0); end
    def setrlimit(*_arg0); end
    def setsid; end
    def spawn(*_arg0); end
    def times; end
    def uid; end
    def uid=(_arg0); end
    def wait(*_arg0); end
    def wait2(*_arg0); end
    def waitall; end
    def waitpid(*_arg0); end
    def waitpid2(*_arg0); end
    def warmup; end
  end
end

class Random < ::Random::Base
  def ==(_arg0); end

  private

  def initialize_copy(_arg0); end
  def left; end
  def marshal_dump; end
  def marshal_load(_arg0); end
  def state; end

  class << self
    def bytes(_arg0); end
    def new_seed; end
    def rand(*_arg0); end
    def seed; end
    def srand(*_arg0); end
    def urandom(_arg0); end

    private

    def left; end
    def state; end
  end
end

class Range
  include ::Enumerable

  def initialize(*_arg0); end

  def %(_arg0); end
  def ==(_arg0); end
  def begin; end
  def bsearch; end
  def count(*_arg0); end
  def cover?(_arg0); end
  def each; end
  def end; end
  def entries; end
  def eql?(_arg0); end
  def exclude_end?; end
  def first(*_arg0); end
  def hash; end
  def inspect; end
  def last(*_arg0); end
  def max(*_arg0); end
  def member?(_arg0); end
  def min(*_arg0); end
  def minmax; end
  def overlap?(_arg0); end
  def reverse_each; end
  def size; end
  def step(*_arg0); end
  def to_a; end
  def to_s; end
  def to_set(*_arg0); end

  private

  def initialize_copy(_arg0); end
end

class Rational < ::Numeric
  def *(_arg0); end
  def **(_arg0); end
  def +(_arg0); end
  def -(_arg0); end
  def -@; end
  def /(_arg0); end
  def <=>(_arg0); end
  def ==(_arg0); end
  def abs; end
  def ceil(*_arg0); end
  def coerce(_arg0); end
  def denominator; end
  def fdiv(_arg0); end
  def floor(*_arg0); end
  def hash; end
  def inspect; end
  def magnitude; end
  def negative?; end
  def numerator; end
  def positive?; end
  def quo(_arg0); end
  def rationalize(*_arg0); end
  def round(*_arg0); end
  def to_f; end
  def to_i; end
  def to_r; end
  def to_s; end
  def truncate(*_arg0); end

  private

  def marshal_dump; end

  class << self
    private

    def convert(*_arg0); end
  end
end

class Regexp
  def initialize(*_arg0); end

  def ==(_arg0); end
  def ===(_arg0); end
  def =~(_arg0); end
  def casefold?; end
  def encoding; end
  def eql?(_arg0); end
  def fixed_encoding?; end
  def hash; end
  def inspect; end
  def match(*_arg0); end
  def match?(*_arg0); end
  def named_captures; end
  def names; end
  def options; end
  def source; end
  def timeout; end
  def to_s; end
  def ~; end

  private

  def initialize_copy(_arg0); end

  class << self
    def compile(*_arg0); end
    def escape(_arg0); end
    def last_match(*_arg0); end
    def linear_time?(*_arg0); end
    def quote(_arg0); end
    def timeout; end
    def timeout=(_arg0); end
    def try_convert(_arg0); end
    def union(*_arg0); end
  end
end

module Signal
  private

  def list; end
  def signame(_arg0); end
  def trap(*_arg0); end

  class << self
    def list; end
    def signame(_arg0); end
    def trap(*_arg0); end
  end
end

# source://shellwords/0.2.2/shellwords.rb#219
class String
  include ::Comparable

  def initialize(*_arg0); end

  def %(_arg0); end
  def *(_arg0); end
  def +(_arg0); end
  def +@; end
  def -@; end
  def <<(_arg0); end
  def <=>(_arg0); end
  def ==(_arg0); end
  def ===(_arg0); end
  def =~(_arg0); end
  def [](*_arg0); end
  def []=(*_arg0); end
  def append_as_bytes(*_arg0); end
  def ascii_only?; end
  def b; end
  def byteindex(*_arg0); end
  def byterindex(*_arg0); end
  def bytes; end
  def bytesize; end
  def byteslice(*_arg0); end
  def bytesplice(*_arg0); end
  def capitalize(*_arg0); end
  def capitalize!(*_arg0); end
  def casecmp(_arg0); end
  def casecmp?(_arg0); end
  def center(*_arg0); end
  def chars; end
  def chomp(*_arg0); end
  def chomp!(*_arg0); end
  def chop; end
  def chop!; end
  def chr; end
  def clear; end
  def codepoints; end
  def concat(*_arg0); end
  def count(*_arg0); end
  def crypt(_arg0); end
  def dedup; end
  def delete(*_arg0); end
  def delete!(*_arg0); end
  def delete_prefix(_arg0); end
  def delete_prefix!(_arg0); end
  def delete_suffix(_arg0); end
  def delete_suffix!(_arg0); end
  def downcase(*_arg0); end
  def downcase!(*_arg0); end
  def dump; end
  def dup; end
  def each_byte; end
  def each_char; end
  def each_codepoint; end
  def each_grapheme_cluster; end
  def each_line(*_arg0); end
  def empty?; end
  def encode(*_arg0); end
  def encode!(*_arg0); end
  def encoding; end
  def end_with?(*_arg0); end
  def eql?(_arg0); end
  def force_encoding(_arg0); end
  def freeze; end
  def getbyte(_arg0); end
  def grapheme_clusters; end
  def gsub(*_arg0); end
  def gsub!(*_arg0); end
  def hash; end
  def hex; end
  def include?(_arg0); end
  def index(*_arg0); end
  def insert(_arg0, _arg1); end
  def inspect; end
  def intern; end
  def length; end
  def lines(*_arg0); end
  def ljust(*_arg0); end
  def lstrip(*_arg0); end
  def lstrip!(*_arg0); end
  def match(*_arg0); end
  def match?(*_arg0); end
  def next; end
  def next!; end
  def oct; end
  def ord; end
  def partition(_arg0); end
  def prepend(*_arg0); end
  def replace(_arg0); end
  def reverse; end
  def reverse!; end
  def rindex(*_arg0); end
  def rjust(*_arg0); end
  def rpartition(_arg0); end
  def rstrip(*_arg0); end
  def rstrip!(*_arg0); end
  def scan(_arg0); end
  def scrub(*_arg0); end
  def scrub!(*_arg0); end
  def setbyte(_arg0, _arg1); end
  def size; end
  def slice(*_arg0); end
  def slice!(*_arg0); end
  def split(*_arg0); end
  def squeeze(*_arg0); end
  def squeeze!(*_arg0); end
  def start_with?(*_arg0); end
  def strip(*_arg0); end
  def strip!(*_arg0); end
  def sub(*_arg0); end
  def sub!(*_arg0); end
  def succ; end
  def succ!; end
  def sum(*_arg0); end
  def swapcase(*_arg0); end
  def swapcase!(*_arg0); end
  def to_c; end
  def to_f; end
  def to_i(*_arg0); end
  def to_r; end
  def to_s; end
  def to_str; end
  def to_sym; end
  def tr(_arg0, _arg1); end
  def tr!(_arg0, _arg1); end
  def tr_s(_arg0, _arg1); end
  def tr_s!(_arg0, _arg1); end
  def undump; end
  def unicode_normalize(*_arg0); end
  def unicode_normalize!(*_arg0); end
  def unicode_normalized?(*_arg0); end
  def upcase(*_arg0); end
  def upcase!(*_arg0); end
  def upto(*_arg0); end
  def valid_encoding?; end

  private

  def initialize_copy(_arg0); end

  class << self
    def new(*_arg0); end
    def try_convert(_arg0); end
  end
end

class Struct
  include ::Enumerable

  def initialize(*_arg0); end

  def ==(_arg0); end
  def [](_arg0); end
  def []=(_arg0, _arg1); end
  def deconstruct; end
  def deconstruct_keys(_arg0); end
  def dig(*_arg0); end
  def each; end
  def each_pair; end
  def eql?(_arg0); end
  def filter(*_arg0); end
  def hash; end
  def inspect; end
  def length; end
  def members; end
  def select(*_arg0); end
  def size; end
  def to_a; end
  def to_h; end
  def to_s; end
  def values; end
  def values_at(*_arg0); end

  private

  def initialize_copy(_arg0); end

  class << self
    def new(*_arg0); end
  end
end

class Symbol
  include ::Comparable

  def <=>(_arg0); end
  def ==(_arg0); end
  def ===(_arg0); end
  def =~(_arg0); end
  def [](*_arg0); end
  def capitalize(*_arg0); end
  def casecmp(_arg0); end
  def casecmp?(_arg0); end
  def downcase(*_arg0); end
  def empty?; end
  def encoding; end
  def end_with?(*_arg0); end
  def inspect; end
  def length; end
  def match(*_arg0); end
  def match?(*_arg0); end
  def next; end
  def size; end
  def slice(*_arg0); end
  def start_with?(*_arg0); end
  def succ; end
  def swapcase(*_arg0); end
  def to_proc; end
  def upcase(*_arg0); end

  class << self
    def all_symbols; end
  end
end

class Thread
  def initialize(*_arg0); end

  def [](_arg0); end
  def []=(_arg0, _arg1); end
  def abort_on_exception; end
  def abort_on_exception=(_arg0); end
  def add_trace_func(_arg0); end
  def alive?; end
  def backtrace(*_arg0); end
  def backtrace_locations(*_arg0); end
  def exit; end
  def fetch(*_arg0); end
  def group; end
  def inspect; end
  def join(*_arg0); end
  def key?(_arg0); end
  def keys; end
  def kill; end
  def name; end
  def name=(_arg0); end
  def native_thread_id; end
  def pending_interrupt?(*_arg0); end
  def priority; end
  def priority=(_arg0); end
  def raise(*_arg0); end
  def report_on_exception; end
  def report_on_exception=(_arg0); end
  def run; end
  def set_trace_func(_arg0); end
  def status; end
  def stop?; end
  def terminate; end
  def thread_variable?(_arg0); end
  def thread_variable_get(_arg0); end
  def thread_variable_set(_arg0, _arg1); end
  def thread_variables; end
  def to_s; end
  def value; end
  def wakeup; end

  class << self
    def abort_on_exception; end
    def abort_on_exception=(_arg0); end
    def current; end
    def each_caller_location(*_arg0); end
    def exit; end
    def fork(*_arg0); end
    def handle_interrupt(_arg0); end
    def ignore_deadlock; end
    def ignore_deadlock=(_arg0); end
    def kill(_arg0); end
    def list; end
    def main; end
    def new(*_arg0); end
    def pass; end
    def pending_interrupt?(*_arg0); end
    def report_on_exception; end
    def report_on_exception=(_arg0); end
    def start(*_arg0); end
    def stop; end
  end
end

class ThreadGroup
  def add(_arg0); end
  def enclose; end
  def enclosed?; end
  def list; end
end

# source://time/0.4.2/time.rb#28
class Time
  include ::Comparable

  def asctime; end
  def ceil(*_arg0); end
  def ctime; end
  def day; end
  def deconstruct_keys(_arg0); end
  def dst?; end
  def floor(*_arg0); end
  def friday?; end
  def getgm; end
  def getlocal(*_arg0); end
  def getutc; end
  def gmt?; end
  def gmt_offset; end
  def gmtime; end
  def gmtoff; end
  def hash; end
  def hour; end
  def inspect; end
  def isdst; end
  def iso8601(*_arg0); end
  def localtime(*_arg0); end
  def mday; end
  def min; end
  def mon; end
  def monday?; end
  def month; end
  def nsec; end
  def round(*_arg0); end
  def saturday?; end
  def sec; end
  def strftime(_arg0); end
  def subsec; end
  def sunday?; end
  def thursday?; end
  def to_a; end
  def to_f; end
  def to_i; end
  def to_r; end
  def to_s; end
  def tuesday?; end
  def tv_nsec; end
  def tv_sec; end
  def tv_usec; end
  def usec; end
  def utc; end
  def utc?; end
  def utc_offset; end
  def wday; end
  def wednesday?; end
  def xmlschema(*_arg0); end
  def yday; end
  def year; end
  def zone; end

  private

  def _dump(*_arg0); end
  def initialize_copy(_arg0); end

  class << self
    def gm(*_arg0); end
    def local(*_arg0); end
    def mktime(*_arg0); end
    def utc(*_arg0); end

    private

    def _load(_arg0); end
  end
end

class TracePoint; end

class TrueClass
  def &(_arg0); end
  def ===(_arg0); end
  def ^(_arg0); end
  def inspect; end
  def to_s; end
  def |(_arg0); end
end

class UnboundMethod
  def ==(_arg0); end
  def arity; end
  def bind(_arg0); end
  def bind_call(*_arg0); end
  def clone; end
  def dup; end
  def eql?(_arg0); end
  def hash; end
  def inspect; end
  def name; end
  def original_name; end
  def owner; end
  def parameters; end
  def source_location; end
  def super_method; end
  def to_s; end
end

module Warning
  extend ::Warning

  def warn(*_arg0); end

  class << self
    def [](_arg0); end
    def []=(_arg0, _arg1); end
    def categories; end
  end
end
